name: Release

on:
  issues:
    types: [ opened ]

jobs:
  check-and-parse-issue:
    if: contains(github.event.issue.labels.*.name, 'Release')
    name: Check And Parse Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: update

      - name: Checkout `metadata` branch
        uses: actions/checkout@v3
        with:
          ref: metadata
          path: metadata
          persist-credentials: false
          clean: false

      - name: Copy files to root directory
        run: |
          cp -r metadata/* ./

      - name: Get Issue Details
        id: issue
        run: |
          ISSUE_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
          ISSUE_DETAILS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $ISSUE_URL)
          echo "$ISSUE_DETAILS" > issue.json
          echo "Issue Details saved to issue.json"
          echo "::set-output name=details::$ISSUE_DETAILS"
      - name: Run script.py
        run: |
          python parse-issue.py
          python downloader.py
          python release.py
      - name: Commit and Push
        run: |
          BRANCH_NAME="temp/release-${{ github.run_number }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git add release/
          git commit -m "release-${{ github.run_number }}" 
          git push origin $BRANCH_NAME



  create_pull_request:
    runs-on: ubuntu-latest
    needs: check-and-parse-issue

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: temp/release-${{ github.run_number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge release files into release branch"
          body: "This PR merges files from the release directory into the release branch."
          base: release
          branch: temp/release-${{ github.run_number }}
          delete-branch: true

      - name: Close Issue
        uses: peter-evans/close-issue@v2.0.0
        with:
          comment: |
            已经发布！