name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Run Python script
        run: |
          python download-file.py
          echo "Download Completed"
          cp daily-update.py Copy-daily-update.py
          git checkout update --force
          python Copy-daily-update.py
          echo "Update Completed"

      - name: Push
        run: |
          
          git add gtnh-assets-wrapper.json mods-versions-wrapper.json version/
          git commit -m "update"
          git push -u origin update
