name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `update` branch
        uses: actions/checkout@v3
        with:
          ref: update

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: List files in root directory
        run: ls -la

      - name: Run Python downloader script
        run: python downloader.py

      - name: List files in root directory
        run: ls -la

      - name: Run Python processor script
        run: python processor.py

      - name: List files in root directory
        run: ls -la

      - name: Checkout `metadata` branch
        uses: actions/checkout@v3
        with:
          ref: metadata
          persist-credentials: false
          clean: false

      - name: List files in root directory
        run: ls -la

      - name: Configure Git
        uses: qoomon/actions--setup-git@v1         

      - name: Commit changes
        run: |
          git add gtnh-assets-wrapper-formatted.json gtnh-assets-wrapper.json
          git commit -m "update"
          git push -u origin metadata

