name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `update` branch
        uses: actions/checkout@v3
        with:
          ref: update

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python script
        run: |
          python downloader.py
          python processor.py

      - name: Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add gtnh-assets-wrapper-formatted.json gtnh-assets-wrapper.json
          git commit -m "update"
          git push -u origin update
